name = "fornax"
main = "build/index.js"
compatibility_date = "2026-07-11"

[build]
command = "node build.mjs"

[assets]
directory = "src-vite/dist"
run_worker_first = ["/api/*"]
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "fornax-db"
database_id = "48975adc-c9d9-4858-bf0d-15f20ac1dc68"
