/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * fornax
 * OpenAPI spec version: 0.1.0
 */
import type { ApiRespSendCodeRespData } from './apiRespSendCodeRespData';
import type { ApiRespSendCodeRespErrors } from './apiRespSendCodeRespErrors';

export interface ApiRespSendCodeResp {
  /** @minimum 0 */
  code: number;
  data?: ApiRespSendCodeRespData;
  /** @nullable */
  errors?: ApiRespSendCodeRespErrors;
  msg: string;
}
