/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * fornax
 * OpenAPI spec version: 0.1.0
 */
import type { ApiRespLoginRespData } from './apiRespLoginRespData';
import type { ApiRespLoginRespErrors } from './apiRespLoginRespErrors';

export interface ApiRespLoginResp {
  /** @minimum 0 */
  code: number;
  data?: ApiRespLoginRespData;
  /** @nullable */
  errors?: ApiRespLoginRespErrors;
  msg: string;
}
