/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * fornax
 * OpenAPI spec version: 0.1.0
 */

/**
 * @nullable
 */
export type ApiRespSendCodeRespErrors = {[key: string]: string[]} | null;
