/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * fornax
 * OpenAPI spec version: 0.1.0
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ApiRespLoginResp,
  ApiRespSendCodeResp,
  LoginReq,
  SendCodeReq
} from './model';

export const getFornax = (axiosInstance: AxiosInstance = axios.default) => {
const root = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/`,options
    );
  }

const login = (
    loginReq: LoginReq, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiRespLoginResp>> => {
    return axiosInstance.post(
      `/api/auth/login`,
      loginReq,options
    );
  }

const sendCode = (
    sendCodeReq: SendCodeReq, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiRespSendCodeResp>> => {
    return axiosInstance.post(
      `/api/auth/send-code`,
      sendCodeReq,options
    );
  }

return {root,login,sendCode}};
export type RootResult = AxiosResponse<void>
export type LoginResult = AxiosResponse<ApiRespLoginResp>
export type SendCodeResult = AxiosResponse<ApiRespSendCodeResp>
